model {
  file: "model.sdf"
}
name: "SANDWICH_MEAL"
description: "SANDWICH MEAL\nThe set includes 2 slices of bread and onion, 1 plate, 1 banana, and 1 slice of cheese, ham, cucumber, and tomato. Great for pretend and imaginative play."
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "PlanToys"
}
annotations {
  key: "mpn"
  value: "3464"
}
annotations {
  key: "sku"
  value: "0346401"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
  first: "Toys"
}
